name: Publish Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: yezz123/setup-uv@v4

      - name: Build project
        run: uv build

      - name: Upload release artifacts
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
